microservice:
  custmer-service:
   endpoints:
     endpoint:
      uri: http://api-gateway/customer/findall
  product-service:
       endpoints:
         endpoint:
           uri: http://api-gateway/product/empleeData
